# Generated by Django 6.0.6 on 2026-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='status',
            field=models.CharField(choices=[('no_work', 'Нет работы'), ('has_work', 'Есть работа'), ('has_mark', 'Есть отметка')], default='no_work', max_length=20),
        ),
    ]
